### ISSUE TITLE
ClassNotFoundException: burp.BurpExtender

### ISSUE THREAD

**Issue by ifrane** [synopsys-sig/ATOR-Burp#2]
Hi,,I'm just trying your plugin but receive this error when loading the .jar into Burp

java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at burp.gbx.a(Unknown Source)
	at burp.gbx.<init>(Unknown Source)
	at burp.gvv.a(Unknown Source)
	at burp.elq.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

This is my Java env:
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

This is my Burp version:
2020.4.1

I used the ator-v2.jar from ATOR-Burp/bin/latest/

**Comment by Manikandanrkdn** [comment]
Not able to replicate the issue right now.
But this issue occurs very rarely while developing/testing, basically if you reload the extension, that will resolve the issue.

**Comment by aditi-synopsys** [comment]
Based on the Java and Burp versions you provided, they appear to be compatible. However, we recommend you to use latest version of ATOR. Particularly we are not facing this issue in any of ATOR version. If you continue to encounter this issue, please let us know and we'll do our best to assist you.

Thank you for choosing our ATOR plugin, closing this ticket for now. Feel free to reopen if required.

**Comment by aditi-synopsys** [comment]
Based on the Java and Burp versions you provided, they appear to be compatible. However, we recommend you to use latest version of ATOR. Particularly we are not facing this issue in any of ATOR version. If you continue to encounter this issue, please let us know and we'll do our best to assist you.

Thank you for choosing our ATOR plugin, closing this ticket for now. Feel free to reopen if required.
